# Setup
title:               analytic cessation
tagline:             'aarush sheth'
description:         'stochastics, optimization, and dynamics</a>.'
url:                 https://aarushsheth.github.io
baseurl:             '/'
paginate:            5
permalink:           pretty
toc: true
toc_sticky: true

# About/contact
author:
  name:              aarush sheth
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
